### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by avi-mastov** [Instabug/Instabug-Flutter#105]
The `Instabug.start` method calls `startWithToken:invocationEvents:` which is the name on iOS, but on Android its name is `start` and it has an extra argument of type `android.app.Application` which can't be passed from Flutter. As a result, the SDK isn't initialized on Android and throws an exception.

**Comment by AliAbdelfattah** [comment]
Hi @avi-mastov, we're still working on unifying Instabug initializing APIs. For the time being, the initialization step is done separately for each platform.

For iOS:
```
    if (Platform.isIOS) {
      Instabug.start('YOUR_TOKEN', <InvocationEvent>[InvocationEvent.floatingButton]);
    }
```

For Android, please check the steps 3, 4, and 5 here: https://github.com/Instabug/Instabug-Flutter#using-instabug. You can also check the example app here: https://github.com/Instabug/Instabug-Flutter/tree/master/example

Let me know how it goes.

**Comment by avi-mastov** [comment]
Hi @AliAbdelfattah thanks for the reply. You can check https://github.com/Instabug/Instabug-Flutter/pull/106 I made for solving the issue without having to work on each platform separately.
