### ISSUE TITLE
errors in logcat for release builds

### ISSUE THREAD

**Issue by FuturistLabs** [Instabug/Instabug-Flutter#108]
I see some errors in the logcat for android release builds.
The app works fine and shows bug report popup on shake event(after a lot of shaking though :) )

I thought is from proguard, but I can see that error logs even with proguard off 

`2020-01-02 15:55:46.424 E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method logUserEventWithName: on channel instabug_flutter)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
    <asynchronous suspension>
    #1      Instabug.logUserEvent (package:instabug_flutter/Instabug.dart:200)
    #2      CrashReporter.log (package:evolutions_flutter/utils/crash_reporter.dart:10)
.......`

**Comment by alyezz** [comment]
@FuturistLabs It might be an issue with flutter caching, can you try running `flutter clean` and uninstalling the app from the device? see (Here)https://github.com/flutter/flutter/issues/12264#issuecomment-508656567]

Let us know if the issue persists
