### ISSUE TITLE
Bug Reporting Support

### ISSUE THREAD

**Issue by leecommamichael** [Instabug/Instabug-Flutter#113]
Google has deprecated Fabric, making Instabug one of the few alternatives to Firebase Crashlytics. In many businesses (including the one I develop for) Google products are not used for security reasons. We'd really like to be able to just drop this into our application, as we're being forced to transition away from Firebase, but without some kind of automatic stack trace reporting, we couldn't justify the investment.

Currently I'm using Dart's Zones (`runZoned`) implementation as a "catch-all" if the VM goes down and printing myself a nice little stack trace, but that doesn't cover potential native code failures.

So my questions are:
- Is this feature planned?
- What are the challenges associated to implementing it from your perspective?
- If implemented, would you support both Dart and native ios/android stack traces?

**Comment by AliAbdelfattah** [comment]
Hi @leecommamichael, Crash Reporting support is on our roadmap. When implemented, it'll be supporting both dart and native stack traces. We also want to make sure it handles essential features like dsym/sourcemap files and grouping similar crashes.

Let me get back to you in a week if you're interested in an ETA as the team is still discussing it.
