### ISSUE TITLE
Android implementation is broken: startWithToken:invocationEvents: not defined

### ISSUE THREAD

**Issue by dustin-graham** [Instabug/Instabug-Flutter#118]
Hello! I'm trying to implement instabug into my Flutter app and I get a MethodChannel exception on startup. 

```
Unhandled Exception: MissingPluginException(No implementation found for method startWithToken:invocationEvents: on channel instabug_flutter)
```

I dug into the code and I found several issues I'd like to report with regard to Android compatibility. 

First, the MethodChannel implementation found in `Instabug.dart`. 
```dart
  /// Starts the SDK.
  /// This is the main SDK method that does all the magic. This is the only
  /// method that SHOULD be called.
  /// The [token] that identifies the app, you can find
  /// it on your dashboard.
  /// The [invocationEvents] are the events that invoke
  /// the SDK's UI.
  static void start(
      String token, List<InvocationEvent> invocationEvents) async {
    final List<String> invocationEventsStrings = <String>[];
    invocationEvents.forEach((e) {
      invocationEventsStrings.add(e.toString());
    });
    final List<dynamic> params = <dynamic>[token, invocationEventsStrings];
    await _channel.invokeMethod<Object>(
        'startWithToken:invocationEvents:', params);
  }
```

The last statement in there is designed to work specifically with iOS's Objective-C implementation. The Android implementation tries to adapt Objective-C message calling semantics to Java method calls like so:

```java
    @Override
    public void onMethodCall(MethodCall call, Result result) {
        Method[] methods = this.getClass().getMethods();
        boolean isImplemented = false;
        String callMethod = call.method;
        if (callMethod.contains(":")) {
            callMethod = call.method.substring( 0, call.method.indexOf(":"));
        }
        for (Method method : methods) {
            if (callMethod.equals(method.getName())) {
                isImplemented = true;
                ArrayList<Object> tempParamValues = new ArrayList<>();
                if (call.arguments != null) {
                    tempParamValues = (ArrayList<Object>) call.arguments;
                }
                Object[] paramValues = tempParamValues.toArray();
                try {
                    Object returnVal = method.invoke(this, paramValues);
                    result.success(returnVal);
                    break;
                } catch (Exception e) {
                    e.printStackTrace();
                    result.notImplemented();
                }
            }
        }
        if (!isImplemented) {
            result.notImplemented();
        }
    }
```

This would probably work except the Java method defined is named `start` not `startWithToken`. This is easy enough to fix, in fact there's an open pull request #106 that does just that. However, mapping Objective-C semantics to Java (and Dart for that matter) is a strange design choice that is bound to introduce breaking bugs like this. In the near term, can you please review and merge #106 ?  In the medium term, I think it would be beneficial to review the plugin design and not base the design on Objective-C. I'm more than happy to contribute a pull request and assist in some of that. However #106 is 3 months outstanding, please review and fix.

**Comment by alyezz** [comment]
@dustin-graham apologies for the delay, however, the `start` method in android is not meant to be called from dart size since the android initialization is required in the application class according to the integration steps [here](https://github.com/Instabug/Instabug-Flutter#using-instabug). In fact if we merge the #106 it would still not work because the initialization on android needs to be done in the application class.

We will add a platform check to prevent this error from appearing but for now, you can safely ignore it.
