### ISSUE TITLE
Could not find com.instabug.library:instabug:9.1.0.0

### ISSUE THREAD

**Issue by Salman-Official** [Instabug/Instabug-Flutter#119]
Tried to integrate with my flutter project, i followd the instruction given on the URL - 

https://dashboard.instabug.com/welcome-to-instabug

but once I run the project it gave me the following error - 

* What went wrong:
Could not determine the dependencies of task ':instabug_flutter:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':instabug_flutter:debugCompileClasspath'.
   > Could not find com.instabug.library:instabug:9.1.0.0.
     Required by:
         project :instabug_flutter

Kindly help me in fixing this.

**Comment by alyezz** [comment]
@Salman-Official sorry for that, the steps you followed seem to be missing step number 2 here: https://github.com/Instabug/Instabug-Flutter#using-instabug 

We will make sure to update them
