### ISSUE TITLE
Documentation lacks info about Release

### ISSUE THREAD

**Issue by adityadroid** [Instabug/Instabug-Flutter#121]
I have been trying to integrate Instabug in our flutter app and have noticed that your documentation does not talk about proguard configuration for release build. Without this the build fails in `--release` mode with reference issues. 
This can be fixed by adding 
```
-dontwarn com.instabug.**
```
to the proguard file at `/android/app/proguard-rules.pro` . I think this should be part of the documentation.
Source for fix from the [React Native SDK](https://github.com/Instabug/Instabug-React-Native/issues/170).

**Comment by AliAbdelfattah** [comment]
@adityadroid Thank you for reporting this, we're looking into it.

**Comment by AliAbdelfattah** [comment]
Hi @adityadroid, we were not able to reproduce this from our side. Could you please send the error messages and if possible the project dependencies?
