### ISSUE TITLE
Feature Request: Ability to hide/dismiss Bug Reporting Screen

### ISSUE THREAD

**Issue by adityadroid** [Instabug/Instabug-Flutter#124]
Our app has a lock screen that gets invoked every time the user leaves the app and comes back. Since Instabug Plugin relies on native Instabug iOS and Android Plugins. Our lock screen is not able to overlay on top of it.

We'd like to dismiss/kill the Bug Reporting Activity programmatically from my dart code. 

The Bug Reporting class currently has a `show()` method to start the feature, It should also have a `hide()` method to dismiss it.

**Comment by AliAbdelfattah** [comment]
@adityadroid sorry for taking a while to get back on this. That looks like a valid use case to add the `hide()` API. While we don't have plans to add this API yet, our product team has taken note of your request and we've added it to our backlog. Thank you for the suggestion!
