### ISSUE TITLE
Ability to change the shaking threshold

### ISSUE THREAD

**Issue by gching** [Instabug/Instabug-Flutter#125]
Hi, just wondering if there is a way to change the shaking threshold. In Android, you could call `BugReporting.setShakingThreshold(800);` but after looking through the code, it doesn't seem like this is exposed publicly. Let me know if there is a way, and if not, then this is a feature request :>

**Comment by AliAbdelfattah** [comment]
@gching thanks for reporting this. As a workaround, for now, you could call it natively in `CustomFlutterApplication.java`, just make sure you call it after invoking/starting Instabug. Give it a try and let me know how it goes.

**Comment by gching** [comment]
@AliAbdelfattah 

I tried doing that at first, but I don't have direct access to the Instabug Android SDK in my `CustomFlutterApplication`. My apologies cause I am not familiar with Android development, but how would I import it directly in `CustomFlutterApplication`? I tried `import com.instabug.bug.BugReporting;` but I think it can't find it cause its a direct dependency

**Comment by alyezz** [comment]
@gching i created a PR for that #133 . will make sure to include it in our next release
