### ISSUE TITLE
Unauthorized error when building android project

### ISSUE THREAD

**Issue by duy-ng-12354** [Instabug/Instabug-Flutter#126]
Hi,

Please help to check this issue which breaks the build of my android project on version 9.1:

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/41779676/81877538-8fa51e80-95af-11ea-90cb-1204b70844a4.png">

The repository config in build.gralde:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/41779676/81877591-a8153900-95af-11ea-8b8d-c75aed5cf2b0.png">

**Comment by AliAbdelfattah** [comment]
@duy-ng-12354 this should be fixed now, can you try again and let me know how it goes please?

**Comment by duy-ng-12354** [comment]
@AliAbdelfattah still the same 😢

**Comment by duy-ng-12354** [comment]
It's ok now @AliAbdelfattah . looks like the change need time to be in place.

Thanks for your fast reaction :)
