### ISSUE TITLE
iOS App crashes due to bug in Instabug v9.1 iOS SDK

### ISSUE THREAD

**Issue by NickJokic** [Instabug/Instabug-Flutter#132]
Hey,

Our Flutter iOS App crashes quite a lot due to some bugs related to **Instabug v9.1**, same one as described in this issue: https://github.com/Instabug/Instabug-iOS/issues/362.

Since this bug is already fixed in the more recent versions of the Instabug iOS SDK, I have 2 questions:

1. Any way to still use this flutter plugin with somehow manually updating iOS pod version of the Instabug SDK? ( e.g. using v9.1.5 instead of 9.1 with this plugin)
2. Or is there a new release scheduled soon for this flutter plugin?

Thank you for your help,
Nick

**Comment by to7be** [comment]
+1

**Comment by alyezz** [comment]
@NickJokic Thanks for reporting this! There is a new release coming in the next few days which will include this fix, i will update you in this thread once its released

**Comment by AliAbdelfattah** [comment]
Fixed in v9.1.6.
