### ISSUE TITLE
Update Android demo for a default Flutter project created with latest Flutter SDK

### ISSUE THREAD

**Issue by mouneyrac** [Instabug/Instabug-Flutter#135]
The demo from the example folder does not seem to have the same architecture than a default project created on the latest Android studio/Flutter SDK. Nothing critical, but worth to update :)

**Comment by mouneyrac** [comment]
My manifest (unchanged default flutter) is:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.bepaw.battlegrounds_stats">
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Bgrounds Stats"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

There is already an application tag and apparently from googling it is supposed to be only one application tag.

**Comment by mouneyrac** [comment]
I am wondering, does Instabug work with a Flutter project using Kotlin (the default way Flutter projects are created at the moment)?

**Comment by mouneyrac** [comment]
I attached a picture below to show the differences between the demo example project and the default Flutter project:
![image](https://user-images.githubusercontent.com/354908/87115602-5387f480-c2a6-11ea-873d-88be40d1183a.png)

**Comment by AliAbdelfattah** [comment]
The example app has been updated.
