### ISSUE TITLE
Invalid Android dependency

### ISSUE THREAD

**Issue by g123k** [Instabug/Instabug-Flutter#138]
Hello,

The Android dependency used by this plugin seems to be wrong:

```
Could not determine the dependencies of task ':instabug_flutter:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':instabug_flutter:debugCompileClasspath'.
   > Could not find com.instabug.library:instabug:9.1.6.0.
     Required by:
         project :instabug_flutter
```

You should replace it with `implementation 'com.instabug.library:instabug:9.1.6'` (9.1.6.0 -> 9.1.6)

**Comment by alyezz** [comment]
Hi @g123k , you've probably missed adding our maven repository. It's mentioned in the first step under android [here](https://github.com/Instabug/Instabug-Flutter#initializing-instabug).

**Comment by KLD** [comment]
The step in missing on the website's welcome screen 

This url: https://dashboard.instabug.com/welcome-to-instabug
