### ISSUE TITLE
[Feature request] Proguard support

### ISSUE THREAD

**Issue by ganeshrvel** [Instabug/Instabug-Flutter#141]
I am getting the following error in the stacktrack which doesn't make any sense.

```
StackTrace: Warning: This VM has been configured to produce stack traces that violate the Dart standard. *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** pid: 32602, tid: 32697, name 1.ui isolate_instructions: 7157d52000 vm_instructions: 7157d4d000 #00 abs 00000071583daad7 virt 000000000068fad7 _kDartIsolateSnapshotInstructions+0x688ad7 #01 abs 0000007157d5953b virt 000000000000e53b _kDartIsolateSnapshotInstructions+0x753b #02 abs 0000007157d59827 virt 000000000000e827 _kDartIsolateSnapshotInstructions+0x7827 #03 abs 00000071582265cf virt 00000000004db5cf _kDartIsolateSnapshotInstructions+0x4d45cf #04 abs 0000007157faeb73 virt 0000000000263b73 _kDartIsolateSnapshotInstructions+0x25cb73 #05 abs 0000007157fae7c7 virt 000
```

I have enables Proguard on my app and it fails to provide the stacktrack. Have a look into this?

**Comment by AliAbdelfattah** [comment]
@ganeshrvel thank you for reporting this. We're looking into it.

**Comment by TheBuggedYRN** [comment]
My apologies @ganeshrvel for the late response!

It seems like these stack traces need to be deobfuscated. There are multiple ways you can do this, find out more [here](https://docs.instabug.com/docs/android-obfuscation#deobfuscating-javakotlin-crashes).

Always feel free to reopen this, if it doesn't solve your issue.

**Comment by ganeshrvel** [comment]
Wow. It only took you 2 years 😂😂🎊

**Comment by TheBuggedYRN** [comment]
@ganeshrvel indeed 2 years was so much, but time flies ⌛ 

It was our bad keeping this open for so long, but now with our team growing we can solve more issues and we will always be here to help in the upcoming ones.
Hope the solution helps you squash some bugs! 🐞
