### ISSUE TITLE
Screenshot InvocationEvent not working on Android and documentation to up-to-date?

### ISSUE THREAD

**Issue by toussam** [Instabug/Instabug-Flutter#150]
Hi :)

I implemented the plugin and noticed that there are a few issues with the InvocationEvents on the Android side.

For the screenshot one, using the start (platform side) or setInvocationEvents (common side) methods is not displaying the pop-in.

--

I also noticed that the documentation is not up-to-date, for the floating button and swipe events, or maybe the mapping was wrongly set?

- Button:

documentation is providing -> INVOCATION_EVENT_BUTTON
value that is actually working -> INVOCATION_EVENT_FLOATING_BUTTON

- Swipe

documentation is providing -> INVOCATION_EVENT_SWIPE
value that is actually working -> INVOCATION_EVENT_TWO_FINGER_SWIPE_LEFT

--

Finally, the last release (9.1.7, currently using the previous one aka 9.1.6) is not available at pub.dev:

https://pub.dev/packages/instabug_flutter/versions

--

I thank you in advance for everything!

Best regards,

**Comment by toussam** [comment]
Hi @alyezz :)

Is it possible to analyze the screenshot invocation not working as expected? 

Our application will be deploy in production very soon and we would like to have this feature.

**Comment by alyezz** [comment]
@toussam very sorry this felt under our radar

Thanks for pointing this out, the documentation has been updated.

As for the screenshot issue you are facing, can you please elaborate and include the integration code?

**Comment by toussam** [comment]
@alyezz, nevermind the screenshot is working perfectly on a physical device. (I used to test my app on an emulator.)

Thank you for your responses and wish you a happy new year in advance!! 🎉
