### ISSUE TITLE
readme.md mentions 1.17 or something else as two paths but doesn't clarify the "something else"

### ISSUE THREAD

**Issue by neiljaywarner** [Instabug/Instabug-Flutter#151]
step 2 under crash reporting gives 2 snippets, one for flutter 1.17 and one for something else.
What is the someting else? versions newer than 1.17?

**Comment by alyezz** [comment]
@neiljaywarner The section you are referring to is for versions **older** than 1.17, we will make sure to clarify that. Thank you
