### ISSUE TITLE
Rename method startWithToken -> start on Android side

### ISSUE THREAD

**Issue by britov** [Instabug/Instabug-Flutter#154]
We have method `start` on dart side and on android platform it throw `No implementation found for method startWithToken:invocationEvents: on channel instabug_flutter`

It happens because on Android side method `startWithToken` had been renamed to `start`

We need to fix it and rename method to `startWithToken` or this method isn't needed for us on android and we need to remove it. Because readme says this metod is needed ony for IOS

**Comment by Mishanya840** [comment]
@alyezz WDYT?

**Comment by AliAbdelfattah** [comment]
Thank you for reporting this and sorry for not getting back to you sooner. While we're looking into it, could you possibly add a platform check before invoking the API?

**Comment by Mishanya840** [comment]
Yes, i can but does it means this method needed only for ios? Can we remove them from android part (.java) ?

**Comment by AliAbdelfattah** [comment]
1. Yes
2. No

To give you more context, the SDK initialization is currently mapped for iOS only; that means you'd need to initialize Android natively.

**Comment by AliAbdelfattah** [comment]
Fixed in `9.2.0-nullsafety.0`
