### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by Poweranimal** [Instabug/Instabug-Flutter#155]
Hi there,

It would be nice, if your Flutter SDK would support Flutter Web.

**Comment by bsameh-at-instabug** [comment]
Hello @Poweranimal, will make sure to let you know if we do at some point. 

Thank you for the suggestion 👍

**Comment by percula** [comment]
Interested in this as well, especially now that Flutter for web is in the Stable channel.

**Comment by wer-mathurin** [comment]
@bsameh-at-instabug any update on this?
