### ISSUE TITLE
How to add Instabug to Kotlin Project

### ISSUE THREAD

**Issue by albatrosify** [Instabug/Instabug-Flutter#161]
While Instabug works fine on iOS, I am stuck with adding it to my Android Project.
The Android Part is based on Kotlin. I am stuck with the following steps:

> If your app supports Android, create a new Java class that extends FlutterApplication and add it to your AndroidManifest.xml.

How can I add Instabug to my Kotlin Flutter Project. Please explain in Detail.

**Comment by guykogus** [comment]
It doesn't matter whether the class is in Java or Kotlin. The important thing is that in AndroidManifest.xml you have
```XML
<application
        android:name=".MyApplication"
        ...
```
Your class will look something like:
```Kotlin
class MyApplication : FlutterApplication() {
    override fun onCreate() {
        super.onCreate()

        InstabugFlutterPlugin().start(
            this,
            BuildConfig.INSTABUG_TOKEN,
            arrayListOf(InstabugFlutterPlugin.INVOCATION_EVENT_SHAKE)
        )
    }
```

**Comment by KLD** [comment]
I've had an issue writing the import statement.

```kotlin
import com.instabug.instabugflutter.InstabugFlutterPlugin;

public class Application: FlutterApplication() {
  override fun onCreate() {
    super.onCreate()

    val invocationEvents = ArrayList<String>()
    invocationEvents.add(InstabugFlutterPlugin.INVOCATION_EVENT_SHAKE)
    InstabugFlutterPlugin().start(this, "your token",invocationEvents)
  }
  }
```

I'll update the second part to what @guykogus wrote as it looks more neat.
