### ISSUE TITLE
Migrate to nullable 

### ISSUE THREAD

**Issue by britov** [Instabug/Instabug-Flutter#169]
Lets migrate to latest flutter 2 with nullable
https://dart.dev/null-safety/migration-guide#step1-wait

**Comment by KLD** [comment]
Any update on this?

**Comment by AliAbdelfattah** [comment]
Hi @britov @KLD, we're currently looking into this and will be updating you once we have an update.

**Comment by via-guy** [comment]
@AliAbdelfattah any update on this? It's blocking our project...

**Comment by Danx0** [comment]
Are there any news or updates around the migration to null safety?

**Comment by AliAbdelfattah** [comment]
Migrated to null safety 🎉
