### ISSUE TITLE
Duplicate code for Flutter and Android

### ISSUE THREAD

**Issue by sherrychhabra51** [Instabug/Instabug-Flutter#181]
I was trying Instabug for Flutter app and followed the steps mentioned in Instabug docs available at:-
https://docs.instabug.com/docs/flutter-integration

As per my observation, we are writing duplicate code in Android and Flutter as step 2 and Java code of step 3 seems to be doing same thing. Also, removal of Flutter code has no impact, so wanted to know for what purposes we need to write code in Flutter files.

**Comment by AliAbdelfattah** [comment]
Hi @sherrychhabra51, the SDK initialization is currently mapped for iOS only, in other words, the Flutter initialization code is currently relevant on the iOS platform only; that means you'd need to initialize Android natively in the java files. If you're not targeting iOS, feel free to skip step 2. Does that answer your question?

**Comment by sherrychhabra51** [comment]
Yes Ali, It does answer to the question that I have.  

I have also suggested some edits for Instabug docs where for example in the below link there is a statement to Import the Instabug class in step 1 but this import is in correct as it refer to the react native sdk and also the syntax as well. 

In the same way if we can specify in the docs that what is required for which purpose that would really be helpful,currently it does not tell you that i need to write code in flutter for targetting IOS files.

**Comment by AliAbdelfattah** [comment]
@sherrychhabra51 thank you for bringing this up, we'll make sure to fix it 🙏
