### ISSUE TITLE
iOS channel methods blocked

### ISSUE THREAD

**Issue by via-guy** [Instabug/Instabug-Flutter#191]
In PR #180 I added a fix for iOS that was reverted in https://github.com/Instabug/Instabug-Flutter/commit/e7bd9ef4e965685cf3777639ff2f0d99cbcb60fc.

I'm not sure why this was done, but it means that if a caller from the Dart code uses `await` then the `Future` will never complete and the app will be blocked.

**Comment by AliAbdelfattah** [comment]
@via-guy thank you, we'll look into it and get back to you.

**Comment by via-guy** [comment]
@AliAbdelfattah any update on this?

**Comment by AliAbdelfattah** [comment]
@via-guy closing the issue now that a fix has been released.
