### ISSUE TITLE
Network Logs not showing in Dashboard

### ISSUE THREAD

**Issue by ArneSaknussemm89** [Instabug/Instabug-Flutter#196]
Upgraded to v10.0.0 and am appreciating the null safe update!

However I tried updating my [fork](https://github.com/ArneSaknussemm89/Instabug-Dio-Interceptor/tree/dio4-support) of the Dio Interceptor so it works with Dio >= 4.0 and Instabug >= 10.0, but I'm not seeing the logs in the dashboard.

I've debugged and walked through the NetworkLogger and it *seems* like it's adding the logs, but I haven't gone too deep down the rabbit hole yet.

Any ideas on what I can try next? (Or thoughts on my changes to the interceptor that might be causing the issue?)

**Comment by AliAbdelfattah** [comment]
@ArneSaknussemm89 thank you for reporting this. We'll look further into this and get back to you.

**Comment by MahmoudMehisen** [comment]
@ArneSaknussemm89 
##  Convert requestBody and responseBody toString to work correctly.
can you change the following code

```dart
return data.copyWith(
      endTime: DateTime.now(),
      duration: data.endTime != null
          ? data.endTime!.millisecondsSinceEpoch -
              data.startTime.millisecondsSinceEpoch
          : 0,
      url: response.requestOptions.uri.toString(),
      method: response.requestOptions.method,
      requestBody: response.requestOptions.data,
      requestHeaders: response.requestOptions.headers,
      contentType: response.requestOptions.contentType,
      status: response.statusCode,
      responseBody: response.data,
      responseHeaders: responseHeaders,
    );
```

with the following code

```dart
return data.copyWith(
      endTime: DateTime.now(),
      duration: data.endTime != null
          ? data.endTime!.millisecondsSinceEpoch -
              data.startTime.millisecondsSinceEpoch
          : 0,
      url: response.requestOptions.uri.toString(),
      method: response.requestOptions.method,
      requestBody: response.requestOptions.data.toString(),
      requestHeaders: response.requestOptions.headers,
      contentType: response.requestOptions.contentType,
      status: response.statusCode,
      responseBody: response.data.toString(),
      responseHeaders: responseHeaders,
    );
```

**Comment by ArneSaknussemm89** [comment]
Made the requested changed and pushed up to that fork; but still not seeing any logs in the dashboard.

**Comment by zaralockheart** [comment]
I am too getting this issue, I tried using interceptor and I thought that something is wrong, but I also tried this (copied from https://pub.dev/packages/instabug_flutter#network-logging)
```
InstabugCustomHttpClient().getUrl(Uri.parse('https://www.google.com/')).then((request) async {
      var response = await request.close();
    });
```

but I don't see any network log after I trigger
```
              Instabug.logUserEvent("TEST CRASH CLICK");
              InstabugLog.logInfo("TEST LOG INFO");
              CrashReporting.reportHandledCrash("TEST CRASH WITH NETWORK", StackTrace.current);
```
`reportHandledCrash`,`logUserEvent` and `logInfo` is showing but no network log detected.

**Comment by ArneSaknussemm89** [comment]
Sorry just got back around to this. Using version 10.8.0 of `instabug_flutter` and branch `dio4-support` of my fork of the Interceptor and still not seeing Network Logs appear in the Instabug Dashboard.

**Comment by shehabeldeenibrahim** [comment]
@ArneSaknussemm89 Unfortunately, we weren’t able to reproduce the bug locally. Is it possible to provide a sample app where the issue is reproducible?
