### ISSUE TITLE
Instabug.setReproStepsMode produces inconsistent behavior

### ISSUE THREAD

**Issue by lisamartin00** [Instabug/Instabug-Flutter#198]
In our app's `main.dart` we have
```
Instabug.start(INSTABUG_TOKEN, [InvocationEvent.shake, InvocationEvent.screenshot]);
Instabug.setReproStepsMode(ReproStepsMode.enabled);
```

Sometimes, the Repro Steps show up in Instabug, but sometimes, they do not.  I've noticed that in some cases I can tap the "Edit list" link and it says "All app screens have been deleted."

<img width="416" alt="Screen Shot 2021-09-03 at 1 18 00 PM" src="https://user-images.githubusercontent.com/6465955/132056472-fae74524-f843-462f-94bd-a1178fb54d6b.png">

Do you know why that would happen and if there is a way to prevent it?

Thanks so much for your time and help!

**Comment by MahmoudMehisen** [comment]
@lisamartin00 Thanks for reporting this. We'll look further into this and get back to you.

**Comment by lisamartin00** [comment]
@MahmoudMehisen following up -  I'm curious if you have been able to reproduce this issue, and whether or not you have any discovered any new information.  Thank you!

**Comment by lisamartin00** [comment]
@MahmoudMehisen I am trying to get you as much information as I can.

fvm flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.61.2)
[✓] Connected device (4 available)

• No issues found!
```

pubspec.yaml:
```
instabug_flutter: ^10.9.1
```

I have followed these steps:
In your Android side:
Instabug.setDebugEnabled(true)

In your iOS side:
Instabug.setSdkDebugLogsLevel(IBGSDKDebugLogsLevel.verbose);

Unfortunately, I am seeing no verbose debug logs added.  Is this where I'm supposed to be checking for those?
<img width="915" alt="Screen Shot 2021-11-11 at 11 15 39 AM" src="https://user-images.githubusercontent.com/6465955/141348709-5055a37c-f7f0-4f35-b07a-22d8982207ad.png">

Another interesting piece of information I just discovered is that if I comment out our use of 
`InstabugDioInterceptor`

I am actually seeing the repro steps go through and our uses of `InstabugLog.logError` etc. seem to be coming through more consistently than before.

I didn't realize that there could be a conflict with that interceptor, but that seems fairly plausible now.  

In pubspec.yaml:
```
instabug_dio_interceptor: ^2.0.1
````

<details>
<summary>In `dio_config.dart`</summary>
```
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:instabug_dio_interceptor/instabug_dio_interceptor.dart';
import 'package:pretty_dio_logger/pretty_dio_logger.dart';
import 'package:spaces/res/constants.dart';
import 'package:spaces/src/di/service_locator.dart';

class DioConfig {
  final String serverUrl = SPACES_API_URL;
  late Dio dio;

  DioConfig({String? bearerToken}) {
    dio = Dio();
    dio.options.headers[HttpHeaders.acceptHeader] = 'application/json';
    dio.options.baseUrl = serverUrl;
    setToken(bearerToken);
    dio.interceptors.addAll([
      InstabugDioInterceptor(),
      ErrorInterceptor(),
      PrettyDioLogger(
        request: false,
        requestHeader: false,
        requestBody: false,
        responseBody: false,
        responseHeader: false,
        error: true,
        compact: false,
      )
    ]);
  }

  DioConfig.custom(Dio dio) {
    this.dio = dio;
  }

  String getToken() {
    return dio.options.headers[HttpHeaders.authorizationHeader];
  }

  setToken(String? token) {
    if (token != null) {
      dio.options.headers[HttpHeaders.authorizationHeader] = 'Bearer $token';
    }
  }
}

class ErrorInterceptor extends Interceptor {
  ErrorInterceptor();

  @override
  Future<void> onError(DioError err, ErrorInterceptorHandler handler) async {
    if (err.response != null && err.response?.statusCode == 401) {
      await sl.getSessionManager().invalidate();
      await sl.getNavigationManager().reset();
    }
    super.onError(err, handler);
  }
}
```

I can file an issue with that repo unless you know of any conflicts for that dio interceptor.

But in regards to the verbose debug logs coming through, do you know anything else I need to try?


Thanks so much!

**Comment by TheBuggedYRN** [comment]
My apologies @lisamartin00 for this taking so much time from our side.

It might be a bit confusing, but there are two types of screeshots in the bug report view:

  1. The screenshot of the screen that "Report a Bug" was invoked from.

     <img width="474" alt="image" src="https://user-images.githubusercontent.com/99807625/185614343-fad4bab9-0986-4f84-b6ba-eadd2066c7e9.png">
 
  2. The Repro Steps screenshots, they are found when you click "Edit list".
     To get this to work, you need to [set up Repro Steps](https://docs.instabug.com/docs/flutter-repro-steps) by adding `InstabugNavigatorObserver` to your app as follows:
     
     ```dart
     MaterialApp(
          navigatorObservers: [InstabugNavigatorObserver()],
      );
     ```

     <img width="474" alt="image" src="https://user-images.githubusercontent.com/99807625/185613584-04261630-4cfb-45c4-9fbe-75fa666044ed.png">
