### ISSUE TITLE
Illegal class access: 'com.instabug.library.util.a' attempting to access 'com.instabug.library.tracking.c'

### ISSUE THREAD

**Issue by Kayson91** [Instabug/Instabug-Flutter#210]
### Steps to Reproduce the Problem
After implementation, Instabug work perfectly on iOS but crash on Android when users click on a TextField in release mode.

### Instabug integration code
`void main() async {
  FlutterError.onError = (FlutterErrorDetails details) {
    Zone.current.handleUncaughtError(details.exception, details.stack!);
  };

  runZonedGuarded(
      () => runApp(Main(initialRoute, box)), CrashReporting.reportCrash);

  await Instabug.start(Credentials.instabugKey, [InvocationEvent.shake]);
}`

### SDK Version
instabug_flutter: ^10.9.1

### Flutter, iOS and Android Versions
Flutter: 2.5.2
Dart: Dart 2.14.3
Android: 11

**Comment by AliAbdelfattah** [comment]
@Kayson91 could you provide the full stack trace please?
