### ISSUE TITLE
Question about the state of Instabug-Dart-http-Adapter

### ISSUE THREAD

**Issue by bluego-joe** [Instabug/Instabug-Flutter#211]
In trying to utilize https://github.com/Instabug/Instabug-Dart-http-Adapter, I found that it has many version incompatibilities with other packages I'm using.

A PR that solves these issues, and appears to be mostly functional, was opened on 12th September: https://github.com/Instabug/Instabug-Dart-http-Adapter/pull/5. I've taken the opportunity to add a couple of minor comments, as well as a more important question about how header field values are supposed to be logged. It would be great to have this issue cleared up, and the PR merged to `master` and released, but there seems to be very little activity on the project.

Is Instabug-Dart-http-Adapter still supported and maintained? And if so, please could some attention be directed toward the aforementioned PR?

**Comment by bluego-joe** [comment]
Hi @AliAbdelfattah, apologies for pinging you again, but do you have any ETA on the PR? We are currently using the branch in our app, but we'd also like the header issue resolved - otherwise we'd need to find an alternative way to add headers to the logs.

**Comment by AliAbdelfattah** [comment]
@bluego-joe it should be released within the next few days, we're trying to address your comments on the PR as well.

**Comment by AliAbdelfattah** [comment]
@bluego-joe v2 has been released.

**Comment by bluego-joe** [comment]
Hi @AliAbdelfattah, thanks for the new release - it's working great for us :)
