### ISSUE TITLE
Is there a way to avoid the scary screen-recording disclaimer on Android until after the user selects from menu?

### ISSUE THREAD

**Issue by bmthorntn** [Instabug/Instabug-Flutter#251]
The native alert about screen-recording is very off-putting especially since it's shown before the Need Help? pop-up.  Is it possible to choose not to prefill the forms with a screenshot if this is what's causing the prompt? 

The native alert also shows every single time that Instabug is invoked if the user chooses not to allow screen recording. 

### Instabug integration code
Instabug.start('foo', [InvocationEvent.shake]);

### SDK Version
11.0.0

### Flutter, iOS and Android Versions
Flutter version 2.10.5
Dart version 2.16.2
Android SDK version 31.0.0

### Device Model
Pixel 3a (but haven't checked on others)

**Comment by DavidMina96** [comment]
Hi @bmthorntn, 

I'd be glad to assist you with your inquiry. Please allow me to clarify the following points:

- The screen casting permission alert is an Android system dialog that we have no control over. It's displayed by the system whenever the app tries to use the media projection service.
- We cache the permission (if granted) within the app instance, so the dialog is expected to show once per app instance.
- To avoid this dialog getting displayed upon invoking the SDK, you can choose to disable the initial screenshot that gets attached to the bug report using this API: 
```BugReporting.setEnabledAttachmentTypes(false, true, true, true); //boolean parameters represent screenshot, extraScreenshot, galleryImage, screenRecording respectively```

**Comment by bmthorntn** [comment]
@DavidMina96 Thanks so much for your help. Point 3 was exactly what I was after! BTW, this wasn't exactly clear from the docs it might be useful for others to add a line in about it there. Thanks again!
