### ISSUE TITLE
bug(ios): only last network request is logged

### ISSUE THREAD

**Issue by golane-august** [Instabug/Instabug-Flutter#258]
### Steps to Reproduce the Problem

- Launch example app with `instabug_http_client`, see custom [example](https://github.com/golane-august/Instabug-Dart-http-Adapter/tree/258-ios-network-logs)
- create multiple requests by hitting plus sign
- Instabug only logs the last request, not the requests before.

See:
https://github.com/Instabug/Instabug-Flutter/blob/6853a2004cda1be95288db0c8d1cffdb42f7089b/lib/src/modules/network_logger.dart#L17
https://github.com/Instabug/Instabug-Flutter/blob/6853a2004cda1be95288db0c8d1cffdb42f7089b/ios/Classes/InstabugFlutterPlugin.h#L446

### Expected Behavior

Logs / Shows all network requests in dashboard

### Actual Behavior

Only logs / shows the last request

### SDK Version

  instabug_flutter: ^11.0.0
  instabug_http_client: ^2.2.1

### Flutter, iOS and Android Versions
Flutter: 3.0.5
ios: 15.5 (emulator)

### [Optional] Project That Reproduces the Issue
https://github.com/golane-august/Instabug-Dart-http-Adapter/tree/258-ios-network-logs

**Comment by TheBuggedYRN** [comment]
Thanks @golane-august for reporting this!
We will look into it and get back to you.

**Comment by TheBuggedYRN** [comment]
Just wanted you to know that the fix is not available in `v11.2.0` 🎉
