### ISSUE TITLE
Instabug Dio Interceptor  not working

### ISSUE THREAD

**Issue by sanalkv** [Instabug/Instabug-Flutter#301]
Thowing error '[Instabug] - IBGCore: Error requestHeaders values should be of type string not __NSArrayM' when ever i call an api.

### Steps to Reproduce the Problem
Call an api, the package reports error in console.

### Expected Behavior
It should record the api call in instabug console

### Actual Behavior
 but instead its throwing error in debug console.

### Instabug integration code
    final dio = Dio();
    dio.options.baseUrl = '###url';
    dio.interceptors.addAll([
      PrettyDioLogger(requestBody: true),
      _interceptorsWrapper(dio),
      InstabugDioInterceptor(),
    ]);

### SDK Version
  instabug_flutter: ^11.3.0
  instabug_dio_interceptor: ^2.1.1

### Flutter, iOS and Android Versions
Flutter 3.3.8
IOS - 16.1

### Device Model
Iphone 11 pro max.

**Comment by TheBuggedYRN** [comment]
Thanks for reporting @sanalkv for reporting this.

Luckily enough, a fix for this issue was published in version `11.5.0` yesterday. So please update to the latest version.
