### ISSUE TITLE
Questions related to usage of tags

### ISSUE THREAD

**Issue by Afsal102** [Instabug/Instabug-Flutter#314]
## Questions and possible Suggestions

1.   Currently when we want to associate a tag to a specific report(can consider as scoped), setting a tag/s will set it globally and further reports also seem to contain the same tags!
- Currently we can only use a workaround to remove these tags manually from the list of appended tags, but this causes some inconsistency issues like, if there are two reports been reported in the same time but the goal was to set the tags only to a specific (maybe first ) report, currently the tags will get applied for both reports, this further causes issues with the reports been sent to slack(specific channels are there for specific tags), based on the docs i couldn't find a proper way to scope the tags or maybe even remove specific tags or even better associate tags for each report a crash, this would resolve the inconsistency issue as well.
- With the current api depending on tags causes the alerts which are setup for specific tags to cause issues, as a workaround for this we were using a custom prefix(or sometimes) in-front of every message so we can update the alerts to check if the message contains the prefix

**Comment by DavidMina96** [comment]
Hi @Afsal102, 

Glad you've reached out! There are generally two ways to add tags: either from the SDK side using our API or from the dashboard; that depends on your use case. 

If you want to tag only specific reports - based on certain conditions - you can achieve that by creating Rules (from the dashboard) that will automatically add those tags to bug/crash reports if they satisfy the chosen conditions. 

If you still have any questions or need help with a particular workflow, please feel free to contact our support team via [support@instabug.com](mailto:support@instabug.com). We'll be happy to assist you further :)
