### ISSUE TITLE
setUserAttribute automatically converts the value into uppercase

### ISSUE THREAD

**Issue by subhash279** [Instabug/Instabug-Flutter#321]
### Steps to Reproduce the Problem
- Call `setUserAttribute` to store any string value.

### Expected Behavior
- It should store the string value in it normal case.

### Actual Behavior
- Instead it stores the uppercase value when I check on Instabug dashboard.

### Instabug integration code

Instabug.setUserAttribute('value',"aBc");
When checked on Instabug dashboard, this value is shown as "ABC".

### SDK Version

10.13.0

### Flutter, iOS and Android Versions
All

**Comment by DavidMina96** [comment]
@subhash279 Upon looking into it, I'd like to clarify that from the dashboard side, not the SDK API, we enforce uppercase letters for the user attributes' keys. This is a design decision intended to match the style of the other bugs state keys on the dashboard. 

If you still have any further questions or a certain use case that we can help with, please feel free to reach out to our support team at [support@instabug.com](mailto:support@instabug.com).

**Comment by subhash279** [comment]
@DavidMina96 thanks for the update. It doesn't really make sense though. If all strings are uppercased, then we lose valuable information. Is there any other way we can store user info on mobile app so that it won't get uppercased.

**Comment by DavidMina96** [comment]
@subhash279 Just to confirm, this API takes two parameters: the first is `value` and the `second` is key. What gets capitalized is the key, but the value itself is kept as is, which I believe is the one you want to preserve its letters' casing. 

Another useful API for storing user data would be `setUserData`. You can take a look at its usage in this docs [section](https://docs.instabug.com/docs/flutter-identify-user#user-data).

**Comment by subhash279** [comment]
@DavidMina96 thanks for letting me know abt `setUserData`
May I know if it that will remain in normal case or will it be uppercased on dashboard as well?

**Comment by DavidMina96** [comment]
@subhash279 Happy to help :)
It'll appear on the dashboard with the same letters casing of the string you pass to the API.

**Comment by subhash279** [comment]
@DavidMina96 I started using `setUserData` but I don't see that anywhere on the dashboard under "User Attributes". Can you pls confirm where it will be shown.

**Comment by subhash279** [comment]
@DavidMina96 thanks for letting me know. I can confirm it is not working then.
I don't see "User Data" under "User Attributes"

**Comment by subhash279** [comment]
@TheBuggedYRN here it is:
`Instabug.setUserAttribute('uid', uid);
        Instabug.setUserData(uid);`

I can see the user attribute uid on dashboard but not userData. As mentioned earlier in this thread, attributes become uppercased by default.
Thanks.

**Comment by TheBuggedYRN** [comment]
@subhash279 Try updating to the latest version. You will need this [migration guide](https://docs.instabug.com/docs/flutter-migration-guide) to help you with v11+ migration.
Also make sure that `uid` is strictly of type `String` and not `dynamic` or `String?`.

**Comment by TheBuggedYRN** [comment]
@subhash279 Please provide us with detailed info for the following items to be able to help with fixing the issue:
1. How and where are you initializing Instabug?
1. How and where are you using `Instabug.setUserData`?
1. Platform (Android or iOS) that the issue happens on.
1. Debug logs for the impacted Platform. You can get that from Android Studio or Xcode after enabling it in `main.dart` file via:
```dart
Instabug.setDebugEnabled(true); // Android
Instabug.setSdkDebugLogsLevel(IBGSDKDebugLogsLevel.verbose); // iOS
```
