### ISSUE TITLE
I am facing this issue and don't know how to resolve :(

### ISSUE THREAD

**Issue by khayargoli** [Instabug/Instabug-Flutter#326]
```
/Users/shraddhashakya/.pub-cache/hosted/pub.dartlang.org/instabug_flutter-11.6.0/ios/Classes/Util/ArgsRegistry.h:2:9: fatal error: 'Instabug/IBGTypes.h' file not found
    #import <Instabug/IBGTypes.h>
            ^~~~~
    1 warning and 1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/tn/w60jd_wn3tg9020v2spcdyl00000gn/T/flutter_tools.SKMFF4/flutter_ios_build_temp_diri1Rxep/temporary_xcresult_bundle


Lexical or Preprocessor Issue (Xcode): 'Instabug/IBGTypes.h' file not found
/Users/shraddhashakya/.pub-cache/hosted/pub.dartlang.org/instabug_flutter-11.6.0/ios/Classes/Util/ArgsRegistry.h:1:8


Could not build the application for the simulator.
Error launching application on iPhone 11.
```
HELP PLEASE :(

**Comment by DavidMina96** [comment]
Hi @khayargoli,

Thank you for reporting the issue. It looks like it has to do with a caching problem. Can you please run the below commands and then try running the app again?

1. `flutter clean`
2. `pod cache clean --all` inside your `ios` directory followed by `pod install`

If you still face the error afterwards, please feel free to re-open the issue. We're always happy to help :)

**Comment by khayargoli** [comment]
I tried the above it did not work then I made a new flutter project and only added instabug package, yet it fails again....

![Uploading Screenshot_2023-01-25_at_13.48.04.png…]()

**Comment by khayargoli** [comment]
The above are details

**Comment by DavidMina96** [comment]
@khayargoli Apologies for any inconvenience this may be causing. To be able to investigate the issue further, can you please share more details on how you integrated the SDK and ran the app on iOS.

**Comment by khayargoli** [comment]
Hello @DavidMina96 Thank you for replying

I am following the steps exactly from here: https://pub.dev/packages/instabug_flutter

**Comment by DavidMina96** [comment]
@khayargoli Great! Can you please elaborate more on whether you run the app from VS Code or Xcode and in which mode (debug/release)? This will be of help while trying to reproduce the issue on our side. Appreciate your cooperation!

**Comment by khayargoli** [comment]
I am running from VScode and its on debug mode. thanks

**Comment by khayargoli** [comment]
Hi @DavidMina96 

Any findings on this? :)

**Comment by DavidMina96** [comment]
Hi @khayargoli, 

We've been trying to replicate the issue you're facing with no luck. Please feel free to reach out to our support team at [support@instabug.com](mailto:support@instabug.com) so that we can schedule a debugging call with you. It might also be a good idea to update to the latest Xcode version 14.2 and see if it resolves the issue. 

Looking forward to hearing back from you!
