### ISSUE TITLE
Getting license error on pod install 

### ISSUE THREAD

**Issue by romk1n** [Instabug/Instabug-Flutter#328]
### Steps to Reproduce the Problem

go to ios directory
run `pod install`

### Expected Behavior
no errors or warnings  given 
### Actual Behavior
warnings gives:

```
[!] A license was specified in podspec `instabug_flutter` but the file does not exist - /Users/***redacted***/ios/.symlinks/plugins/instabug_flutter/LICENSE.md

[!] Unable to read the license file `../LICENSE.md` for the spec `instabug_flutter (11.6.0)`

[!] Unable to read the license file `../LICENSE.md` for the spec `instabug_flutter (11.6.0)`
```

### Instabug integration code

Not required
### SDK Version

11.6.0
### Flutter, iOS and Android Versions
3.7.1, iOS 16.3

**Comment by TheBuggedYRN** [comment]
Thanks for reporting this issue, @romk1n!
We will be working on fixing this issue in our next release.
