### ISSUE TITLE
Dialog box goes white after a brief second

### ISSUE THREAD

**Issue by khayargoli** [Instabug/Instabug-Flutter#344]
Hello,

I am trying to go back from the screen by pressing 'X' button on top left corner when this happens.

Please look at this bug in the video, thanks

https://user-images.githubusercontent.com/9110000/221755778-d87b1749-4d71-44e0-9594-1fc3eba57416.mp4

**Comment by DavidMina96** [comment]
Hi @khayargoli, 

Thank you for reporting this issue. To be able to investigate it further, could you please share more information regarding the SDK version, integration code, and whether the issue occurs on a specific API level?

**Comment by khayargoli** [comment]
Instabug 11.6.0

**Comment by DavidMina96** [comment]
@khayargoli Would it be possible to share the Android API level and device model as well to try replicating this issue on our side?
