### ISSUE TITLE
Cannot change Instabug options on Android.

### ISSUE THREAD

**Issue by HoangKimToi** [Instabug/Instabug-Flutter#350]
I used the function to change the color but nothing changed.

`
Instabug.setPrimaryColor(const Color(0xffE42082)); 
`

**Comment by TheBuggedYRN** [comment]
Thanks for reporting this @HoangKimToi,
Please provide us with the SDK version and the full integration code.

**Comment by HoangKimToi** [comment]
@TheBuggedYRN  Ah. I was able to fix it. This is due to my Instabug options setting order.

When I setPrimaryColor before setColorTheme then setPrimaryColor is not applied.
