### ISSUE TITLE
11.14.0 SDK support

### ISSUE THREAD

**Issue by erikhric** [Instabug/Instabug-Flutter#381]
11.14.0 version was released without support for flutter. When can we expect new release?

**Comment by abdelhamid-f-nasser** [comment]
Hello @erikhric, I apologize for the delayed response. The release is almost out and should be ready by early next week at the latest.

**Comment by abdelhamid-f-nasser** [comment]
Hello, @erikhric!  

Exciting news - the latest SDK version **v11.14.0** has just been released! 🚀 🎊
