### ISSUE TITLE
Missing setPrivateView method

### ISSUE THREAD

**Issue by Tkko** [Instabug/Instabug-Flutter#402]
I can't find the [setPrivateView](https://docs.instabug.com/reference/set-private-view) method in the Instabug Flutter SDK, is this intentional?

We want to prevent screens with sensitive information to be captured.

Plugin version: ^12.1.0

**Comment by abdelhamid-f-nasser** [comment]
Hi @Tkko ,

I apologise for the delayed response and would like to thank you for reporting this issue. 

It's not currently available in the Flutter SDK, however I'll keep you posted for updates in the future.
