### ISSUE TITLE
Feature required: custom report types with callback

### ISSUE THREAD

**Issue by eugenio-tesio-ueno** [Instabug/Instabug-Flutter#513]
## Description

We need to add a custom report type that allow us to take control back using a callback function after the user shakes the phone. This shall live alongside the standard report types. This will allow us to to do things like redirect the user to another route of our current app, push a metric, etc.

The following picture clarifies the requirement.

![image](https://github.com/user-attachments/assets/b9ca3503-d275-477a-906f-b02f0590ce0e)

The following code will help you understand what we expect:

```dart
CustomReportType customOption1 = CustomReportType(
  title: 'Custom option 1', 
  description: 'description 2',
  icon: SvgPicture.asset(
    AssetsHelper.fromPath('/path/to/image1'),
  ),
  callback: () {
    // ...
  }
);

CustomReportType customOption1 = CustomReportType(
  title: 'Custom option 2', 
  description: 'description 2',
  icon: SvgPicture.asset(
    AssetsHelper.fromPath('/path/to/image2'),
  ),
  callback: () {
    // ...
  }
);

BugReporting.setReportTypes([ReportType.bug, customOption1, customOption2]);
```

**Comment by a7medev** [comment]
Hello @eugenio-tesio-ueno!
We don't have an API for directly adding items to the list of report types, but you can still create such a dialog with custom items manually using familiar Flutter widgets and show Instabug's bug reporting screens from there using the `BugReporting.show(ReportType reportType, List<InvocationOption>? invocationOptions)` API (e.g. `BugReporting.show(ReportType.bug)` to report a bug with the default invocation options).

**Comment by eugenio-tesio-ueno** [comment]
With `BugReporting.show()` method and `shake gesture` package https://pub.dev/packages/shake_gesture I was able to create my on dialog and trigger Bug Reporting programmatically.

**Comment by a7medev** [comment]
@eugenio-tesio-ueno Glad to know that you got it working! Thanks for the update. 🙏🏼
