### ISSUE TITLE
Locale enum causes name collision with with Locale class in dart.ui

### ISSUE THREAD

**Issue by bkayfitz-cara** [Instabug/Instabug-Flutter#71]
Flutter provides a Locale class that is used for the localization package.  They can also be provided as a property in Material apps.

If you import the Instabug plugin into a class that is also referencing the built in Locale object, it causes a name collision and the app will not compile.

A simple solution to be to rename the Locale enum to something more generic, like Language or use the built in type instead of defining your own.

This can also be temporarily solved by importing Instabug with an alias
`import 'package:instabug_flutter/instabug_flutter.dart' as InstabugFlutter;`

but that leads to this awkward syntax
`InstabugFlutter.Instabug.start('API_KEY', [InstabugFlutter.InvocationEvent.shake]);`

**Comment by HeshamMegid** [comment]
@bkayfitz-cara thanks for letting us know about this. We're looking into a fix.

**Comment by alyezz** [comment]
@bkayfitz-cara We just Release [v1.0.0-beta.3 | https://github.com/Instabug/Instabug-Flutter/releases/tag/v1.0.0-beta.3]
Update and let us know if you have any issues
