### ISSUE TITLE
Bad android dependancy

### ISSUE THREAD

**Issue by talmor-guy** [Instabug/Instabug-Flutter#79]
The current dependency in android's gradle is 

implementation 'com.instabug.library:instabug:8.4.0.0'

which is not working.

It should be:

implementation 'com.instabug.library:instabug:8.4.0'

**Comment by HeshamMegid** [comment]
You're probably missing [step number 4 here](https://github.com/Instabug/Instabug-React-Native#using-instabug) if you recently updated.

Add it and the dependency will be resolved.

**Comment by talmor-guy** [comment]
My bad... it works now. Thanks!
