### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by talmor-guy** [Instabug/Instabug-Flutter#92]
I need a way to call start and identifyUser from the flutter code because I do not have the user on app start and might not enable instabug for all users. Is there a way of doing this?

**Comment by alyezz** [comment]
@talmor-guy As of right now, you are not able to call `start` from dart side. You can set the invocation event of the SDK to `none` for some users:

`BugReporting.setInvocationEvents([InvocationEvent.none]);`

Also, you can call Identify user from dart using the API below:

`Instabug.identifyUser("USER_EMAIL", "USER_NAME");`
