### ISSUE TITLE
Not possible to create another Application class in Android?

### ISSUE THREAD

**Issue by PritishSawant** [Instabug/Instabug-Flutter#95]
I am trying to integrate Instabug in our Flutter Application. In the installation docs it is mentioned to create "CustomFlutterApplication" but whenever you create a Flutter Project, there is a file called "Flutter Application.kt" already created and it is non editable so how will I write code which you mentioned in the "Flutter Application.kt" file. You can't have two Application files in an Android Project as far as I know.

**Comment by AliAbdelfattah** [comment]
Hi @PritishSawant, after you create the `CustomFlutterApplication`, it should inherit from the already existing `FlutterApplication` class. Then, add this class to the manifest file `android:name=".CustomFlutterApplication"`. Does that make sense?
