### ISSUE TITLE
Could not find com.instabug.library:instabug:8.6.3.1 on latest of v8.6.4

### ISSUE THREAD

**Issue by yongjhih** [Instabug/Instabug-Flutter#96]
https://github.com/Instabug/Instabug-Flutter/blob/v8.6.4/android/build.gradle#L37 (819c29eae66757e3a7e6831e0f79b709c7cc25d6)

```gradle
    implementation 'com.instabug.library:instabug:8.6.3.1'
```

Checked maven central and jcenter, the 8.6.3.1 has been disappeared:

* https://mvnrepository.com/artifact/com.instabug.library/instabug
* https://bintray.com/bintray/jcenter/com.instabug.library%3Ainstabug

|8.7.0 | Central | 0 | Sep, 2019|
|--|--|--|--|
|8.6.3 | Central | 0 | Aug, 2019|
|8.6.2 | Central | 0 | Aug, 2019|
|8.6.1 | Central | 0 | Aug, 2019|
|8.6.0 | Central | 0 | Aug, 2019|

```Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.instabug.library:instabug:8.6.3.1.
     Searched in the following locations:
       - ...
       - https://dl.google.com/dl/android/maven2/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.jar
       - https://jcenter.bintray.com/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.pom
       - https://jcenter.bintray.com/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.jar
       - https://jcenter.bintray.com/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.pom
       - https://jcenter.bintray.com/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.jar
       - https://jcenter.bintray.com/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.pom
       - https://jcenter.bintray.com/com/instabug/library/instabug/8.6.3.1/instabug-8.6.3.1.jar
     Required by:
         project :app > project :instabug_flutter
```

By the way, `com.instabug.library:instabug:8.6.1.0` is also missing on `v8.6.1`, it's ok for old versions if make it deprecated

https://github.com/Instabug/Instabug-Flutter/blob/v8.6.1/android/build.gradle#L37

```gradle
    implementation 'com.instabug.library:instabug:8.6.1.0'
```

https://github.com/Instabug/Instabug-Flutter/blob/v8.6.3/android/build.gradle#L37

```
    implementation 'com.instabug.library:instabug:8.6.3.0'
```

**Comment by AliAbdelfattah** [comment]
Hi @yongjhih, you've probably missed adding our maven repository. It's mentioned in step number 3 [here](https://github.com/Instabug/Instabug-Flutter#using-instabug).

**Comment by yongjhih** [comment]
You are right, I just realized that, I created a new project and missed it.
